In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.Requirement already satisfied: numpy in d:\py\lib\site-packages (1.18.1)



You are using pip version 19.0.3, however version 20.2b1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [2]:
import numpy as np

In [5]:
z=np.ones(10)


In [6]:
z

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
type(z)

numpy.ndarray

In [8]:

z=np.array([1,2,3,4,5])

In [9]:
z

array([1, 2, 3, 4, 5])

In [10]:
z.ndim


1

In [11]:
z.shape

(5,)

In [26]:
a=np.array([[1,2,3,4,5,6,7,8,9],[9,8,7,6,5,4,3,2.4,1]])

In [27]:


a

array([[1. , 2. , 3. , 4. , 5. , 6. , 7. , 8. , 9. ],
       [9. , 8. , 7. , 6. , 5. , 4. , 3. , 2.4, 1. ]])

In [28]:
a.ndim

2

In [29]:
a.shape

(2, 9)

In [33]:
a.reshape(9,2)

array([[1. , 2. ],
       [3. , 4. ],
       [5. , 6. ],
       [7. , 8. ],
       [9. , 9. ],
       [8. , 7. ],
       [6. , 5. ],
       [4. , 3. ],
       [2.4, 1. ]])

In [35]:
a.max()

9.0

In [37]:
a.min()

1.0

In [38]:
a.argmax()

8

In [39]:
a.argmin()

0

In [40]:
a

array([[1. , 2. , 3. , 4. , 5. , 6. , 7. , 8. , 9. ],
       [9. , 8. , 7. , 6. , 5. , 4. , 3. , 2.4, 1. ]])

In [42]:

arr=np.arange(0,11)

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
arr[5]

5

In [45]:
arr[4:8]    

array([4, 5, 6, 7])

In [46]:
arr[-1]

10

In [47]:

arr[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
arr2=np.array([[10,15,20],[25,30,35],[40,45,50]])

In [52]:
arr2

array([[10, 15, 20],
       [25, 30, 35],
       [40, 45, 50]])

In [54]:
arr2[1][2]

35

In [55]:
arr2[:,:]

array([[10, 15, 20],
       [25, 30, 35],
       [40, 45, 50]])

In [56]:
arr2[0:2,1:2]

array([[15],
       [30]])

In [57]:
arr2[1:2,1:]

array([[30, 35]])

In [58]:
arr2[1:2,1:]=[[34,43]]

In [59]:
arr2

array([[10, 15, 20],
       [25, 34, 43],
       [40, 45, 50]])

In [61]:
arr2>45


array([[False, False, False],
       [False, False, False],
       [False, False,  True]])